# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-suffix: "uv"
          ignore-nothing-to-cache: true

      - name: Build package
        run: uv build

      - name: Save dist folder
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: python-package-build
          if-no-files-found: error

  pypi-publish:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: pypi
      url: https://pypi.org/p/pyfwapi

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          path: dist/
          name: python-package-build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
